### ISSUE TITLE
when clicking on a section bar, it goes down

### ISSUE THREAD

**Issue by perefm** [Spontz/Dungeon#10]
1- Open de Demo Editor
2- Without selecting any section, go to File->Open and select another project (I have tried with the "glsl tests.sqlite" that we have on resiilio)
3- On the new project, click on a section bar --> The bar is displaced several rows down

Workaround:
1- Open de Demo Editor
2- Select any section from the default project, then go to File->Open and select another project (I have tried with the "glsl tests.sqlite" that we have on resiilio)
3- On the new project, click on a section bar --> The bar is selected without problems

**Comment by ifernandez** [comment]
@perefm does this still happen? I couldn't reproduce

**Comment by perefm** [comment]
Yes, still happens... but the behaviour is totally random.

**Comment by ifernandez** [comment]
Fixed!
