### ISSUE TITLE
Phoenix support: FBO formats are not correct

### ISSUE THREAD

**Issue by perefm** [Spontz/Dungeon#12]
The formats supported by Phoenix engine are:
![image](https://user-images.githubusercontent.com/4341888/62139471-b082d880-b2e9-11e9-9bc1-b526c05bb465.png)

But in the editor are:
![image](https://user-images.githubusercontent.com/4341888/62139484-b8db1380-b2e9-11e9-8d12-19fe125bbe99.png)

**Comment by ifernandez** [comment]
Fixed
