### ISSUE TITLE
When setting the "from" time value of a section, it sends the "to" value to the engine

### ISSUE THREAD

**Issue by perefm** [Spontz/Dungeon#15]
1- crear una seccion backgroung de 0 a 12 segundos
2- Modificar el "from" a 2 segundos
La seccion debería pintarse de 2 a 12 segundos, pero se pinta de 0 a 2segundos

El tema es que cuando ponemos 2 segundos en el "to" se está enviando como su fuera el "from"

**Comment by ifernandez** [comment]
This has been fixed
