### ISSUE TITLE
When writing the SPO files for the Phoenix engine, the ":" character is not written

### ISSUE THREAD

**Issue by perefm** [Spontz/Dungeon#16]
The ":" character is required for the new formula engine.

For exmaple, the formula:
`uniform float blend v1:=0.5+0.5*sin(t*10);`
Will not work this way:
`uniform float blend v1=0.5+0.5*sin(t*10);`
It needs the ":" before any "="

In this screenshots, the formula looks good on the editor, but when looking on the Data files, the generated SPO have missing thr ":" character:

![image](https://user-images.githubusercontent.com/4341888/62567698-05939100-b88c-11e9-8185-9c529e595568.png)

**Comment by ifernandez** [comment]
Now the character is written
